# Generated by Django 5.2.4 on 2025-07-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_insurance_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment_plan',
        ),
    ]
