# Generated by Django 5.2.4 on 2025-07-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(default='Sample diagnosis'),
            preserve_default=False,
        ),
    ]
