# Generated by Django 5.2.4 on 2025-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_prescription_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(default='Not Specified'),
        ),
    ]
