# Generated by Django 5.2.4 on 2025-07-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_payment_appointment_payment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
    ]
